
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-10
owner: ucsb-cs156-s25
repo_name: team01-s25-10
pull_requests: [{"author":{"id":"U_kgDOB_9cTw","is_bot":false,"login":"andrewc512","name":"Andrew Chen"},"headRefName":"ac-UCSBDiningCommonsMenuItem-create-db","number":43,"title":"ac - create database table for UCSBDiningCommonsMenuItems","url":"https://github.com/ucsb-cs156-s25/team01-s25-10/pull/43"}]
