
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-10
owner: ucsb-cs156-s25
repo_name: team01-s25-10
pull_requests: [{"author":{"id":"U_kgDOCM75PA","is_bot":false,"login":"mHaghighi04","name":""},"headRefName":"mh-reviews-put-requests","number":48,"title":"Mh reviews put requests","url":"https://github.com/ucsb-cs156-s25/team01-s25-10/pull/48"},{"author":{"id":"U_kgDOCM75PA","is_bot":false,"login":"mHaghighi04","name":""},"headRefName":"mh-reviews-get-by-id","number":47,"title":"Mh reviews get by","url":"https://github.com/ucsb-cs156-s25/team01-s25-10/pull/47"},{"author":{"id":"U_kgDOB_9cTw","is_bot":false,"login":"andrewc512","name":"Andrew Chen"},"headRefName":"ac-UCSBDiningCommonsMenuItem-create-controller","number":46,"title":"ac - ucsb dining commons menu item create controller","url":"https://github.com/ucsb-cs156-s25/team01-s25-10/pull/46"},{"author":{"id":"U_kgDOCM75PA","is_bot":false,"login":"mHaghighi04","name":""},"headRefName":"mh-create-menu-item-review-controller","number":45,"title":"Mh create menu item review controller","url":"https://github.com/ucsb-cs156-s25/team01-s25-10/pull/45"},{"author":{"id":"U_kgDOCM75PA","is_bot":false,"login":"mHaghighi04","name":""},"headRefName":"Milad-MenuReview","number":44,"title":"mh - create database table for menu item reviews","url":"https://github.com/ucsb-cs156-s25/team01-s25-10/pull/44"},{"author":{"id":"U_kgDOB_9cTw","is_bot":false,"login":"andrewc512","name":"Andrew Chen"},"headRefName":"ac-UCSBDiningCommonsMenuItem-create-db","number":43,"title":"ac - create database table for UCSBDiningCommonsMenuItems","url":"https://github.com/ucsb-cs156-s25/team01-s25-10/pull/43"}]
